plugins {
    id 'java'
    id 'application'
    id 'jacoco'
}

group = 'ru.nsu.dashkovskii'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.9.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.9.1'
}

test {
    useJUnitPlatform()
}

application {
    mainClass = 'ru.nsu.dashkovskii.Main'
}

jar {
    manifest {
        attributes(
                'Main-Class': application.mainClass
        )
    }
}

jacoco {
    toolVersion = "0.8.11"
}

jacocoTestReport {
    reports {
        xml.required = true
    }
}
